/**
 * W1-T187 production-scale corpus loader — the ONLY reader of `plan.json` / `ledger.ndjson` /
 * `github.json` in this directory (generated by `generate-corpus.mjs`, committed alongside its
 * output so the fixture "lives beside" every test consuming it, per this task's own acceptance
 * wording). >= 200 tasks, >= 18,000 ledger lines — asserted by the callers below, not merely
 * claimed here.
 *
 * Every consumer that needs a fixed clock (the liveness-bound / recent-vs-orphaned split the
 * generator baked in) should inject `now: () => Date.parse(FIXED_NOW_ISO)` — the SAME instant
 * the generator used to compute every "N minutes ago" timestamp in the ledger.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Plan, Task } from "../../../src/lib/plan.js";
import type { GitHub, PrRef } from "../../../src/lib/status.js";

const HERE = dirname(fileURLToPath(import.meta.url));

/** The exact instant `generate-corpus.mjs` anchored every relative timestamp to. */
export const FIXED_NOW_ISO = "2026-07-20T12:00:00.000Z";

/** The acceptance criteria's own scale floor: ">= 200 tasks, >= 18,000 ledger lines". */
export const CORPUS_MIN_TASKS = 200;
export const CORPUS_MIN_LEDGER_LINES = 18_000;

export function loadCorpusTasks(): Task[] {
  return JSON.parse(readFileSync(join(HERE, "plan.json"), "utf8")) as Task[];
}

export function loadCorpusPlan(): Plan {
  const tasks = loadCorpusTasks();
  return { tasks, byId: new Map(tasks.map((t) => [t.id, t])) };
}

export function corpusLedgerPath(): string {
  return join(HERE, "ledger.ndjson");
}

/** Reads + parses `ledger.ndjson` fresh from disk every call — the SAME shape
 * `readLedgerLines` (src/lib/status.ts) produces, kept independent of it so this loader
 * never silently piggybacks on the very function the equivalence test is checking. */
export function loadCorpusLedgerLines(): Array<Record<string, unknown>> {
  return readFileSync(corpusLedgerPath(), "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .map((l) => JSON.parse(l) as Record<string, unknown>);
}

interface GithubFixture {
  prByUrl: Record<string, PrRef>;
  autoMergeArmedUrls: string[];
}

/** A pure, in-memory `GitHub` gateway resolved from `github.json` — never shells `gh`,
 * never touches the network, so the corpus tests run identically in CI and offline. */
export function loadCorpusGithub(): GitHub {
  const fixture = JSON.parse(readFileSync(join(HERE, "github.json"), "utf8")) as GithubFixture;
  const armed = new Set(fixture.autoMergeArmedUrls);
  return {
    prByRef(ref) {
      return fixture.prByUrl[String(ref)] ?? null;
    },
    findMergedByTrailer() {
      // Every merged task in this corpus resolves via rung (a) ledger `pr.opened`, never the
      // trailer search — deliberately, so the corpus stays a pure function of ledger content.
      return null;
    },
    headRefName() {
      return undefined;
    },
    prBody() {
      return undefined;
    },
    autoMergeArmed(prUrl) {
      return armed.has(prUrl);
    },
  };
}
