#!/usr/bin/env bash
# Canonical daemon launcher. GENERATED by deploy/install-host-units.sh — edit that, not this.
# The invocation itself is derived from: deploy/host-update.sh --print-daemon-run
# (run it with RMD_STATE_DIR set; its default points at a volume that may hold no ledger).
set -euo pipefail
STATE_DIR=/home/craigoleyagent/rmd-state2
IMAGE=synthwatcholey0620.azurecr.io/remudero:latest
REVIVAL_LOG=/home/craigoleyagent/rmd-revivals.log
CASH_SECRET_DIR=/home/craigoleyagent/.local/share/remudero/secrets
# W1-T3269 — the checkout this host converges FROM, and the heap the installer requires. Rendered
# in rather than re-derived, so the converge below uses the same inputs this file was rendered with.
# W1-T3604 — daemon freshness sync detaches /home/craigoleyagent/rmd-state2/remudero; worker exhaust keeps it dirty.
# Using it for convergence caused 464 refusals in 7 days; the install tree stays clean and on main.
# /home/craigoleyagent/rmd-state2/daemon-install matches src/lib/install-root.ts's resolveInstallRoot default:
# config.installRoot falls back to config.root plus "daemon-install"; STATE_DIR is config.root here.
# Re-read that resolver if the default moves; this shell renderer cannot import TypeScript.
# W1-T2953 — avoid backticks and dollar-paren here: this unquoted heredoc executes them.
CHECKOUT=/home/craigoleyagent/rmd-state2/daemon-install
UNITS_HEAP_MB=8192
INSTANCE_NAME=
INSTANCE_REGISTRY=
BOOT=0
[ "${1:-}" = "--boot" ] && BOOT=1

# W1-T3233 — THE REVIVAL LOG'S READER. The record below has been written since W1-T2877 and read by
# nothing. On 2026-09-09 a core.bare flag in the state checkout made entrypoint.sh exit 1, and this
# five-minute timer revived the container into the identical death ~90 times across 7h32m of total
# fleet downtime. docker's own --restart=on-failure:5 could not bound it, because recreating the
# container RESETS RestartCount -- the very fact the record exists to make visible.
#
# COUNTS AND ANNOUNCES: it never refuses to revive. The ninety revivals were wasted, not wrong: the
# same watchdog is what recovers a host from a transient, and a bound that gives up is strictly
# worse than the problem. Exit 0 is excluded because --restart=on-failure:5 is deliberate so a
# clean STOP is never undone -- a run of zeros is an operator stopping a healthy fleet.
CRASH_LOOP_RUN=5

# W1-T3268 — A RUN MUST BE CONTIGUOUS IN TIME, NOT ONLY IN THE FILE. MEASURED on this host at
# 2026-09-09T19:18Z the unbounded reader answered "88 1" while the daemon had been running 25
# minutes with RestartCount=0: those 88 were that morning's RESOLVED incident, newest record
# 10:15:01Z. The log is append-only for the host's life, so a resolved run stayed armed forever and
# the next ordinary exit-1 revival would have raised CRASH LOOP on a single transient.
# THE CEILING IS SIZED FROM THE CADENCE: the tick is 5 minutes, so live revivals are ~300s apart
# and the gap to the read was ~9 hours. 1800s sits an order of magnitude clear of both.
CRASH_LOOP_GAP_S=1800

# Seconds since the epoch for an ISO-8601 UTC stamp, computed ARITHMETICALLY: `mktime` is a gawk
# extension absent on other awks, where a missing function is a silent empty result, not an error.
CRASH_LOOP_EPOCH_AWK='
function epoch(ts,   y, mo, d, h, mi, s, yy, era, yoe, doy, doe, days) {
  y = substr(ts, 1, 4) + 0; mo = substr(ts, 6, 2) + 0; d = substr(ts, 9, 2) + 0
  h = substr(ts, 12, 2) + 0; mi = substr(ts, 15, 2) + 0; s = substr(ts, 18, 2) + 0
  if (y == 0) return -1
  yy = (mo <= 2) ? y - 1 : y
  era = int((yy >= 0 ? yy : yy - 399) / 400)
  yoe = yy - era * 400
  doy = int((153 * (mo + ((mo > 2) ? -3 : 9)) + 2) / 5) + d - 1
  doe = yoe * 365 + int(yoe / 4) - int(yoe / 100) + doy
  days = era * 146097 + doe - 719468
  return days * 86400 + h * 3600 + mi * 60 + s
}
'

# Prints "<count> <exit>" for the trailing run of identical NON-ZERO prev_exit values in $1, or
# nothing when there is no such run. Reads the log this same script appends to, so the format has
# exactly one definition. $2 overrides "now" (epoch seconds) so the suite can pin the clock.
crash_loop_signature() {
  awk -v gap="$CRASH_LOOP_GAP_S" -v now="${2:-$(date -u +%s)}" "$CRASH_LOOP_EPOCH_AWK"'
    match($0, /prev_exit=[^ ]+/) {
      e = substr($0, RSTART + 10, RLENGTH - 10)
      t = epoch($1)
      # A gap wider than the ceiling ENDS the run even when the exit code repeats, so two separate
      # incidents sharing an exit code are never summed into one.
      if (e == last && t >= 0 && lastT >= 0 && t - lastT <= gap) { n += 1 } else { n = 1 }
      last = e; lastT = t
    }
    END {
      # And the run must be recent relative to NOW. A run that was dense nine hours ago and then
      # stopped is a resolved incident, which is the case measured on the live host.
      if (last != "" && last != "0" && last != "none" && lastT >= 0 && now - lastT <= gap) print n, last
    }
  ' "$1" 2>/dev/null
}
# W1-T2953: the backticks here were UNESCAPED inside an unquoted heredoc, so bash EXECUTED this
# comment while rendering — printing a syntax error and substituting its empty output into the
# shipped launcher. `--check-crash-loop <log>` prints the signature and exits, touching nothing
# else. It exists so the
# suite can exercise this logic against a fixture without docker, a state root or a real host.
if [ "${1:-}" = "--check-crash-loop" ]; then
  crash_loop_signature "${2:-$REVIVAL_LOG}"
  exit 0
fi

# W1-T3269 — CONVERGE THIS HOST'S OWN UNITS, THE THIRD QUESTION THIS TICK ALREADY ASKS.
#
# The installer had NO automatic caller -- referenced only by its own test, the operator guide and a
# size baseline -- so it converged when a person remembered. MEASURED 2026-09-09: check mode read
# DRIFTED against a checkout clean and exactly at origin/main. The code had shipped that morning;
# the rendered artifact had not. The tick already asks "is the daemon down" and, since W1-T3245,
# "is the image behind"; this is the same question about a third artifact class on the same cadence.
# THREE DECISION FUNCTIONS IN ONE TICK, NEVER ONE WEIGHTED SCORE -- the signals differ in frequency,
# cost and blast radius, so a weighted sum is dominated by the cheapest and most frequent.
# THE REFUSALS ARE THE DELIVERABLE: a five-minute timer holding root write access to systemd units
# is only safe because it declines in every case it cannot justify.
converge_host_units() {
  # A DIRTY OR OFF-MAIN CHECKOUT IS NEVER INSTALLED -- the whole safety argument. Without it a
  # worktree experiment becomes root systemd configuration on the next tick.
  [ -d "$CHECKOUT/.git" ] || { echo "rmd-relaunch: units -- $CHECKOUT is not a checkout; not converging."; return 0; }
  tracked_changes=$(git -C "$CHECKOUT" status --porcelain --untracked-files=no 2>/dev/null || true)
  refusal_since="$STATE_DIR/state/units-converge-refused-since"
  refusal_alerted="$STATE_DIR/state/units-converge-refusal-alerted"
  if [ -n "$tracked_changes" ]; then
    echo "rmd-relaunch: units -- checkout is DIRTY (tracked changes); not converging (an unreviewed tree must never become root config): $tracked_changes"
    # W1-T4076 -- the stamp's directory is NOT guaranteed to exist. A redirection into a missing
    # directory fails in the SHELL, before the command runs, so the trailing `2>/dev/null || true`
    # never sees it and the error leaks to the launcher's own stderr on every tick.
    mkdir -p "$STATE_DIR/state" 2>/dev/null || true
    if [ ! -f "$refusal_since" ]; then
      date -u +%s > "$refusal_since" 2>/dev/null || true
      rm -f "$refusal_alerted" 2>/dev/null || true
    fi
    refused_at=$(cat "$refusal_since" 2>/dev/null || echo "")
    now=$(date -u +%s 2>/dev/null || echo "")
    case "$refused_at:$now" in *[!0-9:]*) : ;; *)
      if [ -n "$refused_at" ] && [ -n "$now" ] && [ "$((now - refused_at))" -ge 21600 ] && [ ! -e "$refusal_alerted" ]; then
        echo "rmd-relaunch: ALERT host unit convergence has been refused for at least 6 hours; tracked paths: $tracked_changes" >&2
        : > "$refusal_alerted" 2>/dev/null || true
      fi
    ;; esac
    return 0
  fi
  rm -f "$refusal_since" "$refusal_alerted" 2>/dev/null || true

  # W1-T3583 -- READABLE AND ON MAIN, BEFORE ANY UPDATE. A detached HEAD, a foreign branch or a
  # corrupted .git is named here and left alone; nothing below this point may switch, rebase or
  # reset it onto main -- only an ff-only merge of a checkout that is ALREADY on it.
  branch=$(git -C "$CHECKOUT" symbolic-ref --quiet --short HEAD 2>/dev/null || echo "")
  if [ "$branch" != "main" ]; then
    echo "rmd-relaunch: units -- checkout is unreadable or not on branch main (branch='${branch:-none}'); not converging." >&2
    return 0
  fi

  # W1-T3583 -- ADVANCE THE ALREADY-TRUSTED CHECKOUT WITHOUT A DAEMON RESTART. runDeployCycle's own
  # fast-forward (deployer.ts's pullFf) runs only behind its restart-pressure decision, so a clean,
  # below-threshold installer-only change never reaches it -- this checkout would otherwise sit
  # fetched-but-unmerged, and the check below would refuse it on every tick forever. FETCH, THEN
  # FF-ONLY MERGE, as the service user -- never a reset, a rebase or a clean. BOTH ARE BEST-EFFORT:
  # a fetch that cannot reach origin (offline tick, no remote configured) must never newly refuse a
  # checkout the OLD comparison below would have accepted, so its failure falls straight through to
  # that same, already-tested comparison rather than returning here. A fetch that DOES succeed but
  # whose merge is refused is a real, named divergence and returns here rather than falling through
  # silently -- that is the one failure this step must still surface on its own.
  if git -C "$CHECKOUT" fetch --quiet origin main 2>/dev/null; then
    if ! git -C "$CHECKOUT" merge --ff-only --quiet origin/main 2>/dev/null; then
      echo "rmd-relaunch: units -- checkout DIVERGED from origin/main (fast-forward refused); not converging." >&2
      return 0
    fi
  fi

  # CHECK BEFORE INSTALL, ALWAYS. The steady state is a silent no-op, which is what makes a converge
  # event rare enough to be worth a record. This is also the FALLBACK comparison for a tick whose
  # fetch above could not run at all: it names the same checkout-is-stale condition the fetch exists
  # to close, rather than a new one.
  head_sha=$(git -C "$CHECKOUT" rev-parse HEAD 2>/dev/null || echo unknown)
  main_sha=$(git -C "$CHECKOUT" rev-parse origin/main 2>/dev/null || echo unknown)
  if [ "$head_sha" = unknown ] || [ "$head_sha" != "$main_sha" ]; then
    echo "rmd-relaunch: units -- checkout is not at origin/main ($head_sha vs $main_sha); not converging."
    return 0
  fi
  INSTALLER_ENV=(RMD_NODE_MAX_OLD_SPACE_MB="$UNITS_HEAP_MB")
  if [ -n "$INSTANCE_NAME" ]; then
    INSTALLER_ENV=(RMD_INSTANCE_REGISTRY="$INSTANCE_REGISTRY")
    if units_check=$(env "${INSTALLER_ENV[@]}" "$CHECKOUT/deploy/install-host-units.sh" --instance "$INSTANCE_NAME" 2>/dev/null); then
      return 0
    fi
  elif units_check=$(env "${INSTALLER_ENV[@]}" "$CHECKOUT/deploy/install-host-units.sh" 2>/dev/null); then
    return 0
  fi

  # W1-T5518 -- --install never retires a LEGACY user unit, so LEGACY-only drift is named, not
  # reinstalled on every tick. MISSING or DRIFTED lines beside it still converge.
  case "$units_check" in
    *"install-host-units: MISSING "*|*"install-host-units: DRIFTED "*) : ;;
    *"install-host-units: LEGACY "*)
      echo "rmd-relaunch: units -- only LEGACY drift, which --install never retires; not converging:" >&2
      printf '%s\n' "$units_check" | grep -F -e 'LEGACY' -e 'retire it' >&2 || true
      return 0
      ;;
  esac

  # Elevation is REQUIRED and never prompted for: the tick runs as the service user while the unit
  # dir is root-owned. No sudo, no converge -- reported, never fatal.
  if ! sudo -n true 2>/dev/null; then
    echo "rmd-relaunch: units -- DRIFTED but cannot elevate (sudo -n refused); leaving them alone." >&2
    return 0
  fi

  echo "rmd-relaunch: units DRIFTED at $head_sha -- converging."
  install_ok=0
  if [ -n "$INSTANCE_NAME" ]; then
    if sudo -n env "${INSTALLER_ENV[@]}" "$CHECKOUT/deploy/install-host-units.sh" --install --instance "$INSTANCE_NAME"; then
      install_ok=1
    fi
  elif sudo -n env "${INSTALLER_ENV[@]}" "$CHECKOUT/deploy/install-host-units.sh" --install; then
    install_ok=1
  fi
  if [ "$install_ok" -eq 1 ]; then
    printf '%s units-converged sha=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$head_sha" >> "$REVIVAL_LOG" 2>/dev/null || true
  else
    echo "rmd-relaunch: units -- converge FAILED; the next tick re-asks." >&2
  fi
  return 0
}

deploy_code_idle() {
  local container="$1" processes dir locks match_status
  if ! processes="$(docker top "$container" -eo pid,args 2>/dev/null)" || [ -z "$processes" ]; then
    echo "rmd-relaunch: deploy code -- worker probe unreadable; deferring." >&2
    return 1
  fi
  if printf '%s\n' "$processes" | grep -E 'claude .*--output-format|codex .*exec' >/dev/null; then
    echo "rmd-relaunch: deploy code -- active workers; deferring." >&2
    return 1
  else
    match_status=$?
    if [ "$match_status" -ne 1 ]; then
      echo "rmd-relaunch: deploy code -- worker probe unreadable (matcher failed); deferring." >&2
      return 1
    fi
  fi
  for dir in "$STATE_DIR/state/inflight" "$STATE_DIR/worktrees"; do
    # Missing lock directories mean no locks; an unreadable existing path is unknown.
    if [ ! -e "$dir" ] && [ ! -L "$dir" ]; then continue; fi
    if [ ! -d "$dir" ] || ! locks="$(find "$dir" -maxdepth 1 -name '*.lock' -print 2>/dev/null)"; then
      echo "rmd-relaunch: deploy code -- lock probe unreadable at $dir; deferring." >&2
      return 1
    fi
    if [ -n "$locks" ]; then
      echo "rmd-relaunch: deploy code -- active locks at $dir; deferring." >&2
      return 1
    fi
  done
}

deploy_code_clean() {
  local code="$STATE_DIR/remudero" edits
  if [ ! -e "$code/.git" ]; then
    echo "rmd-relaunch: deploy code -- checkout missing; deferring." >&2
    return 1
  fi
  if ! edits="$(GIT_OPTIONAL_LOCKS=0 git -C "$code" status --porcelain --untracked-files=all 2>/dev/null)"; then
    echo "rmd-relaunch: deploy code -- status unreadable; deferring." >&2
    return 1
  fi
  if [ -n "$edits" ]; then
    echo "rmd-relaunch: deploy code -- local edits; deferring without discarding them." >&2
    return 1
  fi
}

refresh_deploy_code() {
  local container="$1" code="$STATE_DIR/remudero" install_head
  deploy_code_idle "$container" || return 1
  deploy_code_clean || return 1
  if ! git -C "$code" fetch --quiet origin main 2>/dev/null; then
    echo "rmd-relaunch: deploy code -- fetch failed; deferring." >&2
    return 1
  fi
  if ! git -C "$code" merge-base --is-ancestor HEAD origin/main 2>/dev/null; then
    echo "rmd-relaunch: deploy code -- checkout diverged or ancestry unreadable; deferring." >&2
    return 1
  fi
  if ! install_head="$(git -C "$CHECKOUT" rev-parse HEAD 2>/dev/null)" || [ -z "$install_head" ] ||
     ! git -C "$code" merge-base --is-ancestor "$install_head" origin/main 2>/dev/null; then
    echo "rmd-relaunch: deploy code -- install checkout ancestry unreadable or ahead of origin/main; deferring." >&2
    return 1
  fi
  # The daemon normally boots detached. An ff-only merge advances that HEAD without switching
  # branches, resetting, cleaning, or restarting its already-loaded process.
  deploy_code_idle "$container" || return 1
  deploy_code_clean || return 1
  if ! git -C "$code" merge --ff-only --quiet origin/main 2>/dev/null; then
    echo "rmd-relaunch: deploy code -- fast-forward failed; deferring." >&2
    return 1
  fi
  deploy_code_idle "$container" && deploy_code_clean
}

# W1-T5688 — ACT ON THE PROGRESS VERDICT, NOT ONLY ON A STOPPED CONTAINER. On 2026-10-03 this tick
# revived 14 times into one crash (each prev_restarts=5) and named CRASH LOOP 3h44m in, in a marker
# nothing reads; a wedged-but-running daemon was never acted on at all, because the healthy arm's
# `refresh_deploy_code || exit 0` ended every tick that had workers in flight. Four rungs:
#   capture-diagnostics -- the verb wrote the bundle; this appends one revival-log line naming it.
#   recycle             -- deploy/recycle-container.sh, at most once per WATCHDOG_RECYCLE_GAP_S. A
#                          refusal is logged with its reason and retried on a later tick only.
#   hold-revive         -- the revive arm starts nothing until origin/main's sha or the image id
#                          differs from the one recorded when the loop was named. The hold OUTLIVES
#                          the verdict's 15-minute window: a held daemon writes no boots, so the
#                          verdict would otherwise lapse and revive the same input every ~20 min.
#   none / unreadable   -- everything below runs exactly as before this task.
WATCHDOG_RECYCLE_GAP_S=1800
WATCHDOG_RECYCLE_AT="$STATE_DIR/state/watchdog-recycle-at"
WATCHDOG_HOLD="$STATE_DIR/state/watchdog-hold-revive"
PROGRESS_VERDICT=""
PROGRESS_STATE=""
PROGRESS_ACTION=""

watchdog_stamp() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# A string field of the verdict's one-line JSON (JSON.stringify writes no spaces).
verdict_field() {
  printf '%s\n' "$PROGRESS_VERDICT" | sed -n 's/.*"'"$1"'":"\([^"]*\)".*/\1/p' | head -n 1
}

# RMD_SELF_SYNC_DONE=1 skips checkCliFreshness, which would fetch and fast-forward the tree the
# workers run on -- the very mutation refresh_deploy_code's idle gate exists to withhold.
read_progress_verdict() {
  local rmd="$STATE_DIR/remudero/bin/rmd" out tmo=()
  PROGRESS_VERDICT=""; PROGRESS_STATE=""; PROGRESS_ACTION=""
  [ -x "$rmd" ] || return 0
  command -v timeout >/dev/null 2>&1 && tmo=(timeout 120)
  if ! out="$(cd "$STATE_DIR/remudero" && RMD_SELF_SYNC_DONE=1 ${tmo[@]+"${tmo[@]}"} "$rmd" progress-watchdog --json --state-root "$STATE_DIR/state" 2>/dev/null)"; then
    echo "rmd-relaunch: progress-watchdog -- verdict unreadable; acting as before." >&2
    return 0
  fi
  PROGRESS_VERDICT="$(printf '%s\n' "$out" | grep -E '^\{' | tail -n 1 || true)"
  PROGRESS_STATE="$(verdict_field state)"
  PROGRESS_ACTION="$(verdict_field action)"
  echo "rmd-relaunch: progress-watchdog -- ${PROGRESS_STATE:-UNKNOWN} action=${PROGRESS_ACTION:-none}"
}

note_progress_verdict() {
  [ "$PROGRESS_ACTION" = "capture-diagnostics" ] || return 0
  local dir; dir="$(verdict_field dir)"
  printf '%s watchdog-verdict state=%s action=%s bundle=%s\n' "$(watchdog_stamp)" "$PROGRESS_STATE" \
    "$PROGRESS_ACTION" "${dir:-skipped}" >> "$REVIVAL_LOG" 2>/dev/null || true
}

# Returns 0 only when it RAN recycle-container.sh, so the caller ends the tick on one action.
recycle_on_verdict() {
  local container="$1" now last out rc script="$CHECKOUT/deploy/recycle-container.sh" result reason args=() envs=()
  [ "$PROGRESS_ACTION" = "recycle" ] || return 1
  now="$(date -u +%s)"
  last="$(cat "$WATCHDOG_RECYCLE_AT" 2>/dev/null || true)"
  case "$last" in ''|*[!0-9]*) last="" ;; esac
  if [ -n "$last" ] && [ "$((now - last))" -lt "$WATCHDOG_RECYCLE_GAP_S" ]; then
    echo "rmd-relaunch: progress-watchdog -- a recycle ran $((now - last))s ago; at most one per ${WATCHDOG_RECYCLE_GAP_S}s."
    return 1
  fi
  # STAMPED BEFORE THE ATTEMPT: a refusal is retried on a later tick, never in this one.
  mkdir -p "$STATE_DIR/state" 2>/dev/null || true
  printf '%s\n' "$now" > "$WATCHDOG_RECYCLE_AT" 2>/dev/null || true
  [ -n "$INSTANCE_NAME" ] && args=(--instance "$INSTANCE_NAME")
  [ -n "$INSTANCE_REGISTRY" ] && envs=(RMD_INSTANCE_REGISTRY="$INSTANCE_REGISTRY")
  echo "rmd-relaunch: progress-watchdog -- ${PROGRESS_STATE}; recycling $container via $script."
  if [ ! -f "$script" ]; then
    out="recycle-container.sh missing at $script"; rc=127
  elif out="$(env ${envs[@]+"${envs[@]}"} RMD_STATE_DIR="$STATE_DIR" RMD_DAEMON_CONTAINER="$container" \
      bash "$script" ${args[@]+"${args[@]}"} 2>&1)"; then
    rc=0
  else
    rc=$?
  fi
  printf '%s\n' "$out"
  if [ "$rc" -eq 0 ]; then result=ok; reason=replaced; else
    result=refused
    reason="$(printf '%s\n' "$out" | grep -v '^[[:space:]]*$' | tail -n 1 | tr -s '[:space:]' ' ' || true)"
  fi
  printf '%s watchdog-recycle result=%s rc=%s reason=%s\n' "$(watchdog_stamp)" "$result" "$rc" "${reason:-none}" \
    >> "$REVIVAL_LOG" 2>/dev/null || true
  return 0
}

# "sha=<origin/main> digest=<image id>" -- the two inputs a revive starts from; unreadable = unknown.
revive_input() {
  local code="$STATE_DIR/remudero" sha digest
  git -C "$code" fetch --quiet origin main >/dev/null 2>&1 || true
  sha="$(git -C "$code" rev-parse --verify --quiet origin/main 2>/dev/null || true)"
  digest="$(docker image inspect --format '{{.Id}}' "$IMAGE" 2>/dev/null || true)"
  printf 'sha=%s digest=%s\n' "${sha:-unknown}" "${digest:-unknown}"
}

# An input moved only when BOTH readings are known and differ: an unreadable one is no evidence.
revive_input_changed() {
  local was="$1" now="$2" key a b
  for key in sha digest; do
    a="$(printf '%s\n' "$was" | sed -n 's/.*'"$key"'=\([^ ]*\).*/\1/p')"
    b="$(printf '%s\n' "$now" | sed -n 's/.*'"$key"'=\([^ ]*\).*/\1/p')"
    if [ -n "$a" ] && [ -n "$b" ] && [ "$a" != unknown ] && [ "$b" != unknown ] && [ "$a" != "$b" ]; then return 0; fi
  done
  return 1
}

# The last ledger step of each of the newest $1 daemon boots (run_ids that wrote daemon.paths).
last_steps_before_exit() {
  tail -n 5000 "$STATE_DIR/state/ledger.ndjson" 2>/dev/null | awk -v n="${1:-0}" '
    {
      rid = ""; st = ""
      if (match($0, /"run_id":"[^"]*"/)) rid = substr($0, RSTART + 10, RLENGTH - 11)
      if (match($0, /"step":"[^"]*"/)) st = substr($0, RSTART + 8, RLENGTH - 9)
      if (rid == "" || st == "") next
      if (st == "daemon.paths" && !(rid in seen)) { seen[rid] = 1; order[++k] = rid }
      if (rid in seen) last[rid] = st
    }
    END {
      out = ""; from = k - n + 1; if (from < 1) from = 1
      for (i = from; i <= k; i++) out = out (out == "" ? "" : ",") last[order[i]]
      print out
    }' || true
}

# Returns 0 when the revive must NOT happen this tick.
hold_revive_on_verdict() {
  local was now fb steps line
  if [ ! -f "$WATCHDOG_HOLD" ]; then
    [ "$PROGRESS_ACTION" = "hold-revive" ] || return 1
    now="$(revive_input)"
    fb="$(printf '%s\n' "$PROGRESS_VERDICT" | sed -n 's/.*"failedBoots15m":\([0-9]*\).*/\1/p')"
    steps="$(last_steps_before_exit "${fb:-0}")"
    line="$(watchdog_stamp) crash-loop-hold failed_boots=${fb:-unknown} last_steps=${steps:-unknown} $now"
    mkdir -p "$STATE_DIR/state" 2>/dev/null || true
    printf '%s\n' "$now" > "$WATCHDOG_HOLD" 2>/dev/null || true
    printf '%s\n' "$line" >> "$REVIVAL_LOG" 2>/dev/null || true
    printf '%s\n' "$line" > "$STATE_DIR/state/DAEMON_CRASH_LOOP" 2>/dev/null || true
    echo "rmd-relaunch: CRASH LOOP -- not reviving into the same input ($now). It revives when origin/main or the image changes; rm $WATCHDOG_HOLD to revive anyway." >&2
    return 0
  fi
  was="$(cat "$WATCHDOG_HOLD" 2>/dev/null || true)"
  now="$(revive_input)"
  if revive_input_changed "$was" "$now"; then
    rm -f "$WATCHDOG_HOLD" 2>/dev/null || true
    printf '%s crash-loop-release %s was %s\n' "$(watchdog_stamp)" "$now" "$was" >> "$REVIVAL_LOG" 2>/dev/null || true
    echo "rmd-relaunch: CRASH LOOP hold released -- input changed ($was -> $now); reviving."
    return 1
  fi
  echo "rmd-relaunch: CRASH LOOP hold -- input unchanged ($now); not reviving." >&2
  return 0
}

# THE STOP LEVER OUTRANKS THIS SCRIPT, INCLUDING AT BOOT AND FROM THE WATCHDOG.
if [ -e "$STATE_DIR/state/STOP" ]; then
  echo "rmd-relaunch: state/STOP present -- refusing to start. rm it to resume."
  exit 0
fi

# IDEMPOTENT. A five-minute timer must never disturb a healthy daemon or its in-flight workers.
#
# W1-T3245 — AND THIS IS WHERE A RECYCLE IS CONSIDERED, IN THE SAME TICK. Reconciliation is
# LEVEL-TRIGGERED: this loop already reads observed state ("is the daemon running") and converges,
# so asking "is the image current" is the same loop asking a second question about the same desired
# state. A separate timer would be a second reconciler over one subject.
#
# TWO DECISIONS, NOT ONE SCORE, and only ONE of them belongs here:
#   RESTART (mount-side) is ALREADY HANDLED and is not this tick's business -- the daemon's own
#           freshness check exits 75 and the entrypoint re-fetches, tens of times a day, in seconds.
#           Acting on it here would put a second actor on the daemon's own job and race it.
#   RECYCLE (image-side) has no other actor: nothing INSIDE a container can replace the image it is
#           running on, and this script is the only thing outside it that runs on a cadence.
# The --image-drift-only flag is what makes the tick blind to the first and awake to the second.
#
# THE DECISION IS NOT MADE HERE. The deploy-run supervisor owns it: the idle gate (no worker, no
# in-flight task, bounded by DEPLOY_IDLE_DEFER_CEILING_MS), the drift reading, the health check and
# the rollback -- and it reaches deploy/recycle-container.sh, whose four refusals are the
# deliverable (no credential, workers still running, a failed pull, a digest mismatch). A tick with
# no drift does nothing at all, so this is DRIFT-driven and not clock-driven; the clock only sets
# how often the question is asked.
if [ -n "$(docker ps -q -f name='^remudero-daemon$' 2>/dev/null)" ]; then
  # W1-T3268 -- THE FLAG'S ONLY PATH BACK. The arm that cleared DAEMON_CRASH_LOOP sat on the
  # revival path below, after this very return, so a host that recovered stopped reviving and never
  # reached it. This is the one place the script observes the daemon HEALTHY.
  rm -f "$STATE_DIR/state/DAEMON_CRASH_LOOP" 2>/dev/null || true
  # CONVERGENCE IS LAST AND ONLY WHEN HEALTHY. A DOWN host needs reviving, not tidying, so nothing
  # here runs before the revive decision; boot is excluded because a host coming up is the worst
  # moment to rewrite its units -- the rule W1-T3245 applied to the recycle decision.
  [ "$BOOT" -eq 0 ] && converge_host_units
  if [ "$BOOT" -eq 0 ] && [ -x "$STATE_DIR/remudero/bin/rmd" ]; then
    # W1-T5688: THE VERDICT IS READ BEFORE refresh_deploy_code, whose `|| exit 0` ends every tick
    # with workers in flight -- exactly the ticks a wedged daemon produces.
    read_progress_verdict
    [ "$PROGRESS_STATE" = CRASH_LOOP ] || rm -f "$WATCHDOG_HOLD" 2>/dev/null || true
    note_progress_verdict
    if recycle_on_verdict 'remudero-daemon'; then exit 0; fi
    # W1-T4917: load current deploy code only after a verified idle fast-forward. Running from
    # daemon-install conflates the invoking checkout with the tree deploy-run acts on.
    # Refresh the source CLI before loading it; standalone executable entrypoints own their
    # runtime and retain the supervisor invocation without requiring a source checkout.
    if [ -f "$STATE_DIR/remudero/src/run-task.ts" ]; then
      refresh_deploy_code 'remudero-daemon' || exit 0
    fi
    echo "rmd-relaunch: remudero-daemon healthy -- asking the supervisor whether a RECYCLE is due."
    # W1-T4267: deploy-run reads resourcePolicyDrift for THIS container (named at install time --
    # the rendered launcher has no CONTAINER_NAME of its own) against the build policy it recycles with.
    (cd "$STATE_DIR/remudero" && \
      RMD_RESOURCE_POLICY_CONTAINER='remudero-daemon' RMD_RESOURCE_POLICY_ROLE=build \
      "$STATE_DIR/remudero/bin/rmd" deploy-run --image-drift-only --state-root "$STATE_DIR") || \
      echo "rmd-relaunch: deploy-run reported a problem; the daemon is untouched and the next tick re-asks." >&2
  else
    echo "rmd-relaunch: remudero-daemon already running -- nothing to do."
  fi
  exit 0
fi

# REFUSE AGAINST AN UNMOUNTED STATE ROOT -- the 2026-09-05 fleet-wipe failure mode.
if ! findmnt -no TARGET /mnt/rmd >/dev/null 2>&1; then
  echo "rmd-relaunch: FATAL -- /mnt/rmd is not mounted. Refusing to start against the bare OS disk." >&2
  exit 1
fi
if [ ! -s "$STATE_DIR/state/ledger.ndjson" ]; then
  echo "rmd-relaunch: FATAL -- $STATE_DIR/state/ledger.ndjson missing or empty; wrong volume?" >&2
  exit 1
fi

# W1-T5688 — HOLD, DON'T SPEND A BOOT ON AN UNCHANGED INPUT. Before the revival record, so a held
# tick writes no revive line and the count below only sees boots that actually happened.
read_progress_verdict
note_progress_verdict
if hold_revive_on_verdict; then exit 0; fi

# A REVIVAL MUST LEAVE A TRACE. Recreating the container RESETS docker's RestartCount, so without
# this record a crash loop is invisible: every beat is fresh and every daemon is young.
printf '%s revive boot=%s prev_status=%s prev_exit=%s prev_restarts=%s\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$BOOT" \
  "$(docker inspect remudero-daemon --format '{{.State.Status}}' 2>/dev/null || echo none)" \
  "$(docker inspect remudero-daemon --format '{{.State.ExitCode}}' 2>/dev/null || echo none)" \
  "$(docker inspect remudero-daemon --format '{{.RestartCount}}' 2>/dev/null || echo none)" \
  >> "$REVIVAL_LOG" 2>/dev/null || true

# THE COUNT IS TAKEN AFTER the STOP refusal, the idempotence check and the mount checks, so none of
# their precedence changes. It writes a marker and a log line; the revive below happens regardless.
CRASH_LOOP_SIG="$(crash_loop_signature "$REVIVAL_LOG")"
CRASH_LOOP_N="${CRASH_LOOP_SIG%% *}"
if [ -n "$CRASH_LOOP_SIG" ] && [ "$CRASH_LOOP_N" -ge "$CRASH_LOOP_RUN" ] 2>/dev/null; then
  CRASH_LOOP_EXIT="${CRASH_LOOP_SIG##* }"
  echo "rmd-relaunch: CRASH LOOP -- $CRASH_LOOP_N consecutive revivals from exit $CRASH_LOOP_EXIT. Reviving anyway; this needs a human." >&2
  printf '%s crash-loop count=%s exit=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$CRASH_LOOP_N" "$CRASH_LOOP_EXIT" \
    >> "$REVIVAL_LOG" 2>/dev/null || true
  printf '%s %s consecutive revivals from exit %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$CRASH_LOOP_N" "$CRASH_LOOP_EXIT" \
    > "$STATE_DIR/state/DAEMON_CRASH_LOOP" 2>/dev/null || true
else
  rm -f "$STATE_DIR/state/DAEMON_CRASH_LOOP" 2>/dev/null || true
fi

# A host reboot must recover the same cash credentials as a recycle. Data files are mode 0600;
# their values stay in this process's environment and never enter docker's argv or a unit file.
read_cash_boot_secret() {
  local path="$1" mode value
  [ -f "$path" ] && [ ! -L "$path" ] || return 1
  if mode="$(stat -c '%a' "$path" 2>/dev/null)"; then :
  elif mode="$(stat -f '%Lp' "$path" 2>/dev/null)"; then :
  else mode=""; fi
  [ "$mode" = 600 ] || return 1
  value="$(awk 'NF { count++; last=$0 } END { if (count == 1) print last; else exit 1 }' "$path" 2>/dev/null)" || return 1
  value="${value%$'\r'}"
  [ -n "$value" ] || return 1
  printf '%s' "$value"
}

if [ -z "${RMD_OPENWEIGHT_API_KEY:-}" ]; then
  RMD_OPENWEIGHT_API_KEY="$(read_cash_boot_secret "${RMD_OPENWEIGHT_API_KEY_PATH:-$CASH_SECRET_DIR/openweight-api-key}")" ||
    echo "rmd-relaunch: cash API key unavailable; subscription work remains available" >&2
fi
if [ -z "${RMD_FOUNDRY_CLAUDE_API_KEY:-}" ]; then
  RMD_FOUNDRY_CLAUDE_API_KEY="$(read_cash_boot_secret "${RMD_FOUNDRY_CLAUDE_API_KEY_PATH:-$CASH_SECRET_DIR/foundry-claude-api-key}")" ||
    echo "rmd-relaunch: Foundry key unavailable; cash Opus remains unavailable" >&2
fi
if [ -z "${RMD_FOUNDRY_CLAUDE_ENDPOINT:-}" ]; then
  RMD_FOUNDRY_CLAUDE_ENDPOINT="$(read_cash_boot_secret "${RMD_FOUNDRY_CLAUDE_ENDPOINT_PATH:-$CASH_SECRET_DIR/foundry-claude-endpoint}")" ||
    echo "rmd-relaunch: Foundry endpoint unavailable; cash Opus remains unavailable" >&2
fi
export RMD_OPENWEIGHT_API_KEY RMD_FOUNDRY_CLAUDE_API_KEY RMD_FOUNDRY_CLAUDE_ENDPOINT

docker rm -f remudero-daemon >/dev/null 2>&1 || true

SCRATCH_ARGS=()
if [ -r /usr/local/bin/rmd-scratch-mounts ]; then
  . /usr/local/bin/rmd-scratch-mounts
  if scratch_plan "$STATE_DIR" remudero-daemon && scratch_prepare; then scratch_fresh_tmp; fi
  echo "rmd-relaunch: scratch mounts $SCRATCH_NOTE"
fi

CREDENTIAL_ARGS=()


# --restart=on-failure:5 IS DELIBERATE: exit 0 is a STOP and must not be undone. Reboot survival is
# rmd-fleet.service; crash recovery past the budget is rmd-fleet-watchdog.timer.
# NODE_OPTIONS: without it V8 caps at ~2GB and the retro rung aborts at ~2046 MB on a 7.9GB host.
docker run -d --name remudero-daemon \
  --restart=on-failure:5 \
  --cap-drop ALL \
  --security-opt seccomp=unconfined \
  --security-opt apparmor=unconfined \
  --security-opt systempaths=unconfined \
  --user 1000:1000 \
  -e GH_APP_ID=4648213 \
  -e GH_APP_INSTALLATION_ID=155256285 \
  -e GH_APP_PRIVATE_KEY_PATH=/home/node/.claude/rmd-app.pem \
  -e NODE_OPTIONS=--max-old-space-size=8192 \
  -e RMD_RESTART_THROTTLE_S=120 \
  -e RMD_FRESHNESS_RESTART_MAX=100 \
  -e RMD_OPENWEIGHT_API_KEY \
  -e RMD_FOUNDRY_CLAUDE_API_KEY \
  -e RMD_FOUNDRY_CLAUDE_ENDPOINT \
  -v /home/craigoleyagent/.codex:/home/node/.codex \
  -v /home/craigoleyagent/.config/remudero-container:/home/node/.config/remudero \
  -v "$STATE_DIR":/home/node/Remudero \
  -v /home/craigoleyagent/.claude:/home/node/.claude \
  "${CREDENTIAL_ARGS[@]+"${CREDENTIAL_ARGS[@]}"}" \
  "${SCRATCH_ARGS[@]+"${SCRATCH_ARGS[@]}"}" \
  "$IMAGE" \
  ./bin/rmd daemon --repo remudero --allow-self-target

echo "rmd-relaunch: started remudero-daemon (boot=$BOOT)"
